main: spider.Spider
name: Spider
version: 1.0
commands:
     ban:
         description: permet de bannir un joueur.
     kick:
         description: permet de kick un joueur.
     mute:
         description: permet de mute un joueur.
     randomtp:
         description: teleporte aleatoirement a un joueur.